name: Deploy Todo Application

on: 
  push:
    branches:
      - main  # Adjust if necessary

jobs:
  deploy:
    runs-on: self-hosted  # or ubuntu-latest if using GitHub's runner
    steps:
      - name: Login to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

      - name: Delete old container
        run: sudo docker rm -f todo-app-container

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 3000:3000 --name todo-app-container -e MONGO_URI='${{ secrets.MONGO_URI }}' ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
