name: Deploy Todo Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t yourdockerhubusername/todo-backend .
        
      - name: Publish Image to Docker Hub
        run: docker push yourdockerhubusername/todo-backend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull yourdockerhubusername/todo-backend:latest
        
      - name: Delete old container
        run: docker rm -f todo-app-container
        
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name todo-app-container -e MONGO_URI='${{ secrets.MONGO_URI }}' yourdockerhubusername/todo-backend
