name: Deploy Todo Application

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-backend .
        
      - name: Publish Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Clean up Docker system
        run: sudo docker system prune -a -f

      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest

      - name: Delete old container
        run: sudo docker rm -f todo-app-container || true

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 3000:3000 --name todo-app-container ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
